baseurl: "/"
permalink: pretty
title: 'Behavioural Data Science incubator'
title_footer: 'BDSi'
future: true

exclude:
  - "_utils"

collections:
  services:
    output: true
    permalink: /:collection/:title
  partners:
    output: false
  team:
    output: false
  communities:
    output: true
    permalink: /:collection/:title
  blogs:
    output: true
    permalink: /:collection/:title
  projects:
    output: true
    permalink: /:collection/:title
  events:
    output: true
    permalink: /:collection/:title
  news:
    output: true
    permalink: /:collection/:title
  archive:
    output: true
    permalink: /:collection/:title

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: default
  - scope:
      path: ''
      type: news
    values:
      layout: news
      bodyClass: page-news-single
  - scope:
      path: ''
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: ''
      type: blogs
    values:
      layout: blog
      bodyClass: page-blogs-single
  - scope:
      path: ''
      type: projects
    values:
      layout: project
      bodyClass: page-projects-single
  - scope:
      path: ''
      type: events
    values:
      layout: event
      bodyClass: page-single
  - scope:
      path: images
    values:
      image: true
  - scope:
      path: ''
      type: communities
    values: 
      layout: community
      bodyClass: page-single

sass:
  style: expanded # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-redirect-from
